package com.avnixm.avdibook.ui.theme

import androidx.compose.ui.graphics.Color

val BluePrimaryLight = Color(0xFF2D5BCE)
val OnBluePrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFDCE1FF)
val OnBluePrimaryContainerLight = Color(0xFF00174A)
val IndigoSecondaryLight = Color(0xFF545E7D)
val OnIndigoSecondaryLight = Color(0xFFFFFFFF)
val IndigoSecondaryContainerLight = Color(0xFFDCE2FF)
val OnIndigoSecondaryContainerLight = Color(0xFF111B36)
val OrchidTertiaryLight = Color(0xFF6E5B9A)
val OnOrchidTertiaryLight = Color(0xFFFFFFFF)
val OrchidTertiaryContainerLight = Color(0xFFECDDFF)
val OnOrchidTertiaryContainerLight = Color(0xFF28144F)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF9F9FF)
val OnBackgroundLight = Color(0xFF1A1B22)
val SurfaceLight = Color(0xFFF9F9FF)
val OnSurfaceLight = Color(0xFF1A1B22)
val SurfaceVariantLight = Color(0xFFE2E2EC)
val OnSurfaceVariantLight = Color(0xFF45464F)
val OutlineLight = Color(0xFF757680)

val BluePrimaryDark = Color(0xFFB7C4FF)
val OnBluePrimaryDark = Color(0xFF002A77)
val BluePrimaryContainerDark = Color(0xFF1243B4)
val OnBluePrimaryContainerDark = Color(0xFFDCE1FF)
val IndigoSecondaryDark = Color(0xFFBEC6EB)
val OnIndigoSecondaryDark = Color(0xFF27304C)
val IndigoSecondaryContainerDark = Color(0xFF3D4664)
val OnIndigoSecondaryContainerDark = Color(0xFFDCE2FF)
val OrchidTertiaryDark = Color(0xFFD1BEFF)
val OnOrchidTertiaryDark = Color(0xFF3E2B68)
val OrchidTertiaryContainerDark = Color(0xFF554280)
val OnOrchidTertiaryContainerDark = Color(0xFFECDDFF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF12131A)
val OnBackgroundDark = Color(0xFFE2E2EC)
val SurfaceDark = Color(0xFF12131A)
val OnSurfaceDark = Color(0xFFE2E2EC)
val SurfaceVariantDark = Color(0xFF45464F)
val OnSurfaceVariantDark = Color(0xFFC5C6D0)
val OutlineDark = Color(0xFF8F909A)
