package com.avnixm.avdibook.ui.theme

import androidx.compose.ui.graphics.Color

val AmberPrimaryLight = Color(0xFF7A5300)
val OnAmberPrimaryLight = Color(0xFFFFFFFF)
val AmberPrimaryContainerLight = Color(0xFFFFDEA9)
val OnAmberPrimaryContainerLight = Color(0xFF271900)
val OliveSecondaryLight = Color(0xFF5C6132)
val OnOliveSecondaryLight = Color(0xFFFFFFFF)
val OliveSecondaryContainerLight = Color(0xFFE1E7AB)
val OnOliveSecondaryContainerLight = Color(0xFF1A1D00)
val SlateTertiaryLight = Color(0xFF3A6270)
val OnSlateTertiaryLight = Color(0xFFFFFFFF)
val SlateTertiaryContainerLight = Color(0xFFBFE9FA)
val OnSlateTertiaryContainerLight = Color(0xFF001F28)
val ErrorLight = Color(0xFFB3261E)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFF9DEDC)
val OnErrorContainerLight = Color(0xFF410E0B)
val BackgroundLight = Color(0xFFF8F4EC)
val OnBackgroundLight = Color(0xFF1E1B16)
val SurfaceLight = Color(0xFFFDF8F1)
val OnSurfaceLight = Color(0xFF1E1B16)
val SurfaceVariantLight = Color(0xFFEAE1D3)
val OnSurfaceVariantLight = Color(0xFF4C463D)
val OutlineLight = Color(0xFF7D766C)

val AmberPrimaryDark = Color(0xFFF1BC62)
val OnAmberPrimaryDark = Color(0xFF412D00)
val AmberPrimaryContainerDark = Color(0xFF5C4000)
val OnAmberPrimaryContainerDark = Color(0xFFFFDEA9)
val OliveSecondaryDark = Color(0xFFC5CB90)
val OnOliveSecondaryDark = Color(0xFF2F330C)
val OliveSecondaryContainerDark = Color(0xFF454A1E)
val OnOliveSecondaryContainerDark = Color(0xFFE1E7AB)
val SlateTertiaryDark = Color(0xFFA4CDDE)
val OnSlateTertiaryDark = Color(0xFF043543)
val SlateTertiaryContainerDark = Color(0xFF214A58)
val OnSlateTertiaryContainerDark = Color(0xFFBFE9FA)
val ErrorDark = Color(0xFFF2B8B5)
val OnErrorDark = Color(0xFF601410)
val ErrorContainerDark = Color(0xFF8C1D18)
val OnErrorContainerDark = Color(0xFFF9DEDC)
val BackgroundDark = Color(0xFF13110D)
val OnBackgroundDark = Color(0xFFEAE2D8)
val SurfaceDark = Color(0xFF1A1712)
val OnSurfaceDark = Color(0xFFEAE2D8)
val SurfaceVariantDark = Color(0xFF34302A)
val OnSurfaceVariantDark = Color(0xFFD1C5B7)
val OutlineDark = Color(0xFF978F84)

val PureBlack = Color(0xFF000000)
