package com.avnixm.avdibook.ui.theme

import androidx.compose.ui.graphics.Color

val BluePrimaryLight = Color(0xFF2E5BFF)
val OnBluePrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFDCE5FF)
val OnBluePrimaryContainerLight = Color(0xFF0C1B57)
val IndigoSecondaryLight = Color(0xFF5E6C84)
val OnIndigoSecondaryLight = Color(0xFFFFFFFF)
val IndigoSecondaryContainerLight = Color(0xFFE0E6F2)
val OnIndigoSecondaryContainerLight = Color(0xFF1B273D)
val OrchidTertiaryLight = Color(0xFF5870A0)
val OnOrchidTertiaryLight = Color(0xFFFFFFFF)
val OrchidTertiaryContainerLight = Color(0xFFDCE8FF)
val OnOrchidTertiaryContainerLight = Color(0xFF102543)
val ErrorLight = Color(0xFFC62828)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFE0E0)
val OnErrorContainerLight = Color(0xFF5F1111)
val BackgroundLight = Color(0xFFF7F8FA)
val OnBackgroundLight = Color(0xFF161B24)
val SurfaceLight = Color(0xFFF7F8FA)
val OnSurfaceLight = Color(0xFF161B24)
val SurfaceVariantLight = Color(0xFFECEFF4)
val OnSurfaceVariantLight = Color(0xFF4C5668)
val OutlineLight = Color(0xFF7A8496)

val BluePrimaryDark = Color(0xFF8FA8FF)
val OnBluePrimaryDark = Color(0xFF0B1A54)
val BluePrimaryContainerDark = Color(0xFF24356D)
val OnBluePrimaryContainerDark = Color(0xFFDCE5FF)
val IndigoSecondaryDark = Color(0xFFAAB4C8)
val OnIndigoSecondaryDark = Color(0xFF1A2336)
val IndigoSecondaryContainerDark = Color(0xFF323D53)
val OnIndigoSecondaryContainerDark = Color(0xFFD8E1F3)
val OrchidTertiaryDark = Color(0xFF96B4E8)
val OnOrchidTertiaryDark = Color(0xFF11233F)
val OrchidTertiaryContainerDark = Color(0xFF2C4268)
val OnOrchidTertiaryContainerDark = Color(0xFFDCE8FF)
val ErrorDark = Color(0xFFEF5350)
val OnErrorDark = Color(0xFF300504)
val ErrorContainerDark = Color(0xFF5F1B1A)
val OnErrorContainerDark = Color(0xFFFFDAD9)
val BackgroundDark = Color(0xFF121418)
val OnBackgroundDark = Color(0xFFE6EAF2)
val SurfaceDark = Color(0xFF121418)
val OnSurfaceDark = Color(0xFFE6EAF2)
val SurfaceVariantDark = Color(0xFF1D2128)
val OnSurfaceVariantDark = Color(0xFFBCC5D6)
val OutlineDark = Color(0xFF8791A4)

val PureBlack = Color(0xFF000000)
